#!/QOpenSys/usr/bin/sh
export PWD=$(pwd)
system -kpieb "CRTBNDRPG PGM(OSSILE/LISTMEMBER) SRCSTMF('$PWD/listmember.rpgle') TEXT('List source file members') "
exec system -kpieb "RUNSQLSTM SRCSTMF('$PWD/udtf_list_source_member.sql') DFTRDBCOL(OSSILE) "