#!/QOpenSys/usr/bin/sh
export PWD=$(pwd)

export SRCLIB=OSSFTPSRC
export OLIB=OSSFTPCLT

if [ ! -e /qsys.lib/$SRCLIB.lib ] ; then
  system "crtlib $SRCLIB"
fi
if [ ! -e /qsys.lib/$OLIB.lib ] ; then
  system "crtlib $OLIB"
fi


system -kpieb "CRTSRCPF FILE($SRCLIB/QCLSRC) RCDLEN(150)"
system -kpieb "CRTSRCPF FILE($SRCLIB/QCMDSRC) RCDLEN(150)"
system -kpieb "ADDPFM FILE($SRCLIB/QCLSRC) MBR(CRTOBJS) SRCTYPE(CLLE)"
system -kpieb "CPYFRMSTMF FROMSTMF('$PWD/qclsrc/crtobjs.clle') TOMBR('/QSYS.LIB/$SRCLIB.LIB/QCLSRC.FILE/CRTOBJS.MBR') MBROPT(*REPLACE)"
system -kpieb "ADDPFM FILE($SRCLIB/QCMDSRC) MBR(CRTOBJS) SRCTYPE(CMD)"
system -kpieb "CPYFRMSTMF FROMSTMF('$PWD/qcmdsrc/crtobjs.cmd') TOMBR('/QSYS.LIB/OSSFTPSRC.LIB/QCMDSRC.FILE/CRTOBJS.MBR') MBROPT(*REPLACE)"
system -kpieb "CRTCLPGM PGM($SRCLIB/CRTOBJS) SRCFILE($SRCLIB/QCLSRC)"
system -kpieb "CRTCMD CMD($SRCLIB/CRTOBJS) PGM($SRCLIB/CRTOBJS) SRCFILE($SRCLIB/QCMDSRC)"
echo system -kpieb "$SRCLIB/CRTOBJS TGTLIB($OLIB) SRCLIB($SRCLIB) RLSLVL(*CURRENT) DIR('$PWD/')  "
system -kpieb "$SRCLIB/CRTOBJS TGTLIB($OLIB) SRCLIB($SRCLIB) RLSLVL(*CURRENT) DIR('$PWD/')  "

# clean up the source files etc
system -kpieb "DLTLIB LIB($SRCLIB)"
if [ ! -e /qsys.lib/$OLIB.lib/FTPCLIENT.CMD ] ; then
  exit 5
fi
if [ ! -e /qsys.lib/$OLIB.lib/FTPCMAIN.MENU ] ; then
  exit 5
fi
