#!/QOpenSys/usr/bin/sh
export PWD=$(pwd)

export SRCLIB=OSSFTPSRC
export OLIB=OSSFTPCLT

if [ ! -e /qsys.lib/$SRCLIB.lib ] ; then
  system "crtlib $TGTLIB"
fi
if [ ! -e /qsys.lib/$OLIB.lib ] ; then
  system "crtlib $TGTLIB"
fi

system -kpieb "CRTLIB LIB($SRCLIB)"
system -kpieb "ADDLIBLE LIB($SRCLIB)"
system -kpieb "CRTSRCPF FILE($SRCLIB/QCLSRC) RCDLEN(150)"
system -kpieb "CRTSRCPF FILE($SRCLIB/QCMDSRC) RCDLEN(150)"
system -kpieb "ADDPFM FILE($SRCLIB/QCLSRC) MBR(CRTOBJS) SRCTYPE(CLLE)"
system -kpieb "CPYFRMSTMF FROMSTMF('&DIR/qclsrc/crtobjs.clle') TOMBR('/QSYS.LIB/$SRCLIB.LIB/QCLSRC.FILE/CRTOBJS.MBR')"
system -kpieb "ADDPFM FILE($SRCLIB/QCMDSRC) MBR(CRTOBJS) SRCTYPE(CMD)"
system -kpieb "CPYFRMSTMF FROMSTMF('&DIR/qcmdsrc/crtobjs.cmd') TOMBR('/QSYS.LIB/OSSFTPSRC.LIB/QCMDSRC.FILE/CRTOBJS.MBR')"
system -kpieb "CRTCLPGM PGM($SRCLIB/CRTOBJS) SRCFILE($SRCLIB/QCLSRC)"
system -kpieb "CRTCMD CMD($SRCLIB/CRTOBJS) PGM(*LIBL/CRTOBJS) SRCFILE($SRCLIB/QCMDSRC)"
system -kpieb "$SRCLIB/CRTOBJS TGTLIB($OLIB) SRCLIB($SRCLIB) RLSLVL(*CURRENT) DIR('&DIR/')  "
system -kpieb "RMVLIBLE LIB($SRCLIB)"
# clean up the source files etc
system -kpieb "DLTLIB LIB($SRCLIB)
if [ ! -e /qsys.lib/$OLIB.lib/CRTOBJS.PGM ] ; then
  exit 5
fi
if [ ! -e /qsys.lib/$OLIB.lib/CRTOBJS.CMD ] ; then
  exit 5
fi
