#!/QOpenSys/usr/bin/sh
export PWD=$(pwd)
system -kpieb "CRTCMOD MODULE(OSSILE/DSPTRGINF) SRCSTMF('$PWD/dsptrginf.c') REPLACE(*YES)"
system -kpieb "CRTPGM PGM(OSSILE/DSPTRGINF) MODULE(OSSILE/DSPTRGINF)"