#!/QOpenSys/usr/bin/sh
export PWD=$(pwd)
system -kpieb "CRTSRCPF FILE(OSSILE/SU) RCDLEN(92)"
system -kpieb "CPYFRMSTMF FROMSTMF('$PWD/su.clle') TOMBR('/QSYS.lib/OSSILE.lib/SU.file/sucl.mbr') MBROPT(*REPLACE)"
system -kpieb "CPYFRMSTMF FROMSTMF('$PWD/su.cmd') TOMBR('/QSYS.lib/OSSILE.lib/SU.file/su.mbr') MBROPT(*REPLACE)"
system -kpieb "CPYFRMSTMF FROMSTMF('$PWD/su_dspf.dspf') TOMBR('/QSYS.lib/OSSILE.lib/SU.file/su_dspf.mbr') MBROPT(*REPLACE)"
system -kpieb "CRTDSPF FILE(OSSILE/SU_DSPF) SRCFILE(OSSILE/SU) SRCMBR(SU_DSPF) TEXT('SU Display File')"
system -kpieb "CRTBNDCL PGM(OSSILE/SU) SRCFILE(OSSILE/SU) SRCMBR(SUCL) ALWRTVSRC(*YES) REPLACE(*YES) TEXT('SU CPP Program')"
system -kpieb "CRTCMD CMD(OSSILE/SU) PGM(OSSILE/SU) SRCFILE(OSSILE/SU) SRCMBR(SU) PRDLIB(OSSILE) REPLACE(*YES) TEXT('SU Command')"
system -kpieb "DLTOBJ OBJ(OSSILE/GETIPTF) OBJTYPE(*FILE)"