#!/QOpenSys/usr/bin/sh
export PWD=$(pwd)
system -kpieb "CRTCMOD MODULE(OSSILE/CHKRCVRDLT) SRCSTMF('$PWD/chkrcvrdlt.c') REPLACE(*YES)"
system -kpieb "CRTPGM PGM(OSSILE/CHKRCVRDLT) MODULE(OSSILE/CHKRCVRDLT)"