#!/QOpenSys/usr/bin/sh
export PWD=$(pwd)

if [ -e /qsys.lib/ossile.lib/arraylist.file ] ; then
  system -kpieb "DLTOBJ OBJ(OSSILE/ARRAYLIST) OBJTYPE(*FILE)"
fi
system -kpieb "CRTSRCPF FILE(OSSILE/ARRAYLIST) RCDLEN(112)"
system -kpieb "CPYFRMSTMF FROMSTMF('$PWD/arraylist.bnd') TOMBR('/QSYS.LIB/OSSILE.LIB/ARRAYLIST.FILE/ARRAYLIST.MBR') MBROPT(*REPLACE)"

if [ -e /qsys.lib/ossile.lib/arraylist.module ] ; then
  system -kpieb "DLTOBJ OBJ(OSSILE/ARRAYLIST) OBJTYPE(*MODULE)"
fi
system -kpieb "CRTRPGMOD OSSILE/ARRAYLIST SRCSTMF('arraylist.rpgle') OPTION(*SRCSTMT) DBGVIEW(*LIST) OPTIMIZE(*BASIC) STGMDL(*INHERIT)"

if [ -e /qsys.lib/ossile.lib/arraylist.srvpgm ] ; then
  system -kpieb "DLTOBJ OBJ(OSSILE/ARRAYLIST) OBJTYPE(*SRVPGM)"
fi
system -kpieb "CRTSRVPGM OSSILE/ARRAYLIST MODULE(OSSILE/ARRAYLIST) STGMDL(*INHERIT) EXPORT(*SRCFILE) SRCFILE(OSSILE/ALISTSRV) TEXT('Arraylist')"

# cleanup
system -kpieb "DLTOBJ OBJ(OSSILE/ARRAYLIST) OBJTYPE(*FILE)"
system -kpieb "DLTOBJ OBJ(OSSILE/ARRAYLIST) OBJTYPE(*MODULE)"

# check if service program has been built successfully
if [ ! -e /qsys.lib/ossile.lib/arraylist.srvpgm ] ; then
  exit 5
fi

# copy copybook to OSSILE include directory if is is specified and does exit
if [[ $OSSILE_INCDIR != "" ]] ; then
  if [[ ! -e $OSSILE_INCDIR ]] ; then
    echo "include directory $OSSILE_INCDIR does not exist"
  else
    
    if [ ! -e $OSSILE_INCDIR/arraylist ] ; then
      mkdir $OSSILE_INCDIR/arraylist
    fi
    
    cp $PWD/arraylist_h.rpgle $OSSILE_INCDIR/arraylist/arraylist_h.rpgle
    
  fi
fi
