#!/QOpenSys/usr/bin/sh
export PWD=$(pwd)
system -kpieb "CRTCMOD MODULE(OSSILE/SRVPGMCHK) SRCSTMF('$PWD/srvpgmchk.c') REPLACE(*YES)"
exec system -kpieb "CRTPGM PGM(OSSILE/SRVPGMCHK) MODULE(OSSILE/SRVPGMCHK)"